name: coco
description: "CodeCamp Mobile 01 Final Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1
  dropdown_search: ^6.0.2
  apptomate_custom_list_tile: ^0.0.3
  flutter_slidable: ^4.0.0
  sliver_app_bar_builder: ^1.1.0
  calendar_date_picker2: ^2.0.0
  day_night_time_picker: ^1.3.1
  pull_to_refresh: ^2.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  gif: ^2.3.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/loading/
    - assets/logo/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/logo.png"

flutter_native_splash:
  color: "#5CB15A"
  image: "assets/logo/logo.png"
  android: true
  android_12:
    color: "#5CB15A"
  ios: false
